export const MULTIPLAYER_TIMING = Object.freeze({
    inputLeadTicks: 30,
    maxFutureTicks: 36,
    inputHoldTicks: 30,
    remoteInterpolationSeconds: 0.1,
    deadReckoningMaxSeconds: 0.12,
    remotePlayerInterpolationSeconds: 0.05,
    remotePlayerMaxInterpolationSeconds: 0.2,
    remotePlayerJitterSmoothingRatio: 0.125,
    remotePlayerJitterBufferMultiplier: 2,
    remotePlayerPlaybackRateAdjustment: 0.2,
    remotePlayerPresentationSmoothingSeconds: 0.03,
    remotePlayerPresentationSnapDistance: 160,
    remoteClockCorrectionRatio: 0.125,
    remoteClockMaxCorrectionSeconds: 0.05,
    ownerCorrectionSeconds: 0.1,
    ownerHardSnapDistance: 160,
    maxHitClaimPastTicks: 36,
    impactRecoveryRetentionTicks: 1200,
    hitClaimPositionTolerance: 40
});
